spring.application.name=fars

spring.threads.virtual.enabled=true

spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.database=fars_db

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=fars-group


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer